name: "Update Tagged Releases"
on:
  schedule:
  - cron: "30 8 1 * *"
  workflow_dispatch:

jobs:
  refresh-modules:
    name: Refresh Release Submodules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: releases
        submodules: recursive
    - name: Merge upstream changes to releases branch
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git merge origin/master --strategy-option theirs || true
        git submodule foreach 'git reset HEAD $path'   
        git submodule foreach 'git checkout `git describe --tags $(git rev-list --tags --max-count=1)`'  || true
        
        cd processing/wirecloud/wirecloud
        git checkout 1.3.1
        cd ../../..
        
        cd third-party/domibus
        git checkout 5.0
        cd ../..
        
        cd core/apollo
        git checkout 0.0.20
        cd ../../..

        cd core/quantum-leap
        git checkout 1.0.0
        cd ../../..

        cd data-publication/business-api/charging-backend
        git checkout 10.4.0
        cd ../../..

        cd robotics/Fast-DDS
        git checkout v3.3.0
        cd ../../..

        cd security/dsba-pdp
        git checkout 1.2.0
        cd ../../..

        cd security/trusted-issuers-registry
        git checkout 0.3.4
        cd ../../..

        git add -A .
        git commit -m "Merge master into releases" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: releases
        force: true
    - name: Summarize latest releases
      run: |
        SUMMARY=$(git submodule -q foreach '  echo $(basename `git rev-parse --show-toplevel`) `git describe --tags $(git rev-list --tags --max-count=1)`'  || true)
        echo $SUMMARY 
